[package]
name = "bma423"
version = "0.1.0"
edition = "2021"
authors = ["Pierre-Yves Aillet <pyaillet@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
embedded-hal = "^0.2"
num_enum = { version = "^0.5", default-features = false }
accelerometer = { version = "^0.12", optional = true }
bitmask-enum = { version = "^1.1" }

[features]
default = []
accel = [ "accelerometer" ]
